name = "hackathon2-icap"
compatibility_date = "2024-11-27"
pages_build_output_dir = "dist"

# Development variables (non-sensitive)
[vars]
DJANGO_API_URL = "http://localhost:8000"
NODE_ENV = "development"

# KV Namespace for caching (will create this via CLI)
# [[kv_namespaces]]
# binding = "KV"
# id = "to-be-created"

# Preview environment (for PRs and testing)
[env.preview]
vars = { DJANGO_API_URL = "https://api-psycho.edgar-gomero.workers.dev", NODE_ENV = "preview" }

# Production environment (main branch uses default name above)
[env.production]
vars = { DJANGO_API_URL = "https://api-psycho.edgar-gomero.workers.dev", NODE_ENV = "production" }

# Secrets (set via: wrangler secret put SECRET_NAME)
# - DJANGO_API_KEY (optional, for API authentication if needed)
# - JWT_SECRET (optional, for frontend session management if needed)
